# Build Options
<<<<<<< HEAD
AUDIO_ENABLE = yes
=======
AUDIO_ENABLE = no
>>>>>>> master
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = no
MIDI_ENABLE = no
MOUSEKEY_ENABLE = no
NKRO_ENABLE = yes
RGBLIGHT_ENABLE = no
STENO_ENABLE = yes
VIRTSER_ENABLE = yes

